len_per_input_seq: 100
len_per_output_seq: 30
interval: 50
frame_stride: 5

batch_size: 128
learning_rate: 0.001
epochs: 5
use_gpu: true
num_workers: 32
optimizer: "AdamW"
weight_decay: 0.01

hidden_dim: 256