#the total length of the input sequence
len_per_input_seq: 100
#the total length of the output sequence
len_per_output_seq: 30
#the interval between two pieces
interval: 50
#the frame stride of the input and output sequence
frame_stride: 5

batch_size: 128
learning_rate: 0.0005
epochs: 5
model: "simple_mlp"
use_gpu: true
num_workers: 32
optimizer: "AdamW"
weight_decay: 0.01

hidden_dim: 256